version: '3.8'

services:
  backend:
    build:
      context: ./backend  # Look inside the backend folder
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - CORS_ORIGINS=*

  frontend:
    build:
      context: ./frontend # Look inside the frontend folder
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend